# Builds a .NET framework project
name: Nightly builds

env:
  projectName: OpenFK
  projectFolder: OpenFK
  solutionFile: OpenFK.sln

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]
        platform: [ x64, x86 ]
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      
      - name: Restore Packages
        run: nuget restore ${{ env.solutionFile }}

      - name: Fetch Flash.OCX
        shell: cmd
        run: FetchOCX.bat
      
      - name: Move Flash.OCX to path
        run: |
          mkdir path_dir
          mv Flash.OCX path_dir/Flash.OCX
          echo "${{ github.workspace }} ${{ github.workspace }}\path_dir"
          echo "${{ github.workspace }}\path_dir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Generate AxShockwaveFlashObjects.dll and ShockwaveFlashObjects.dll
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\aximp.exe" "${{ github.workspace }}\path_dir\Flash.OCX" /nologo /source
      
      - name: Build solution
        run: msbuild ${{ env.solutionFile }} -t:rebuild -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}
      
      - name: Upload the build results as an artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.projectFolder }}/bin/${{ matrix.platform }}/${{ matrix.configuration }}/*
          name: ${{ env.projectName }}.Nightly.${{ matrix.configuration }}.${{ matrix.platform }}
