# Builds a .NET framework project
name: Nightly builds

env:
  projectName: OpenFK
  projectFolder: OpenFK
  solutionFile: OpenFK.sln

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]
        platform: [ x64, x86 ]
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      
      - name: Restore Packages
        run: nuget restore ${{ env.solutionFile }}

      - name: Fetch Flash.OCX
        shell: cmd
        run: FetchOCX.bat
      
      - name: Download RegSvrEx
        run: Invoke-WebRequest https://github.com/vadz/RegSvrEx/releases/download/v1.0.0.1/RegSvrEx.exe -OutFile RegSvrEx.exe
      
      - name: Register Flash.OCX
        run: |
          ./RegSvrEx.exe /c "${{ github.workspace }}\Flash.ocx"
      
      - name: Build solution
        run: msbuild ${{ env.solutionFile }} -t:rebuild -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}
      
      - name: Upload the build results as an artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.projectFolder }}/bin/${{ matrix.platform }}/${{ matrix.configuration }}/*
          name: ${{ env.projectName }}.Nightly.${{ matrix.configuration }}.${{ matrix.platform }}
